name: Pull Request Workflow And Push
on: 
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR
  issues: write

jobs:
 build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        id: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        id: build-with-maven
        run: mvn -B --no-transfer-progress compile

      - name: Unit test
        id: run-test
        run: mvn -B test

      - name: Coverage report
        id: coverage-report
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 10